-- axr_trade_manager npc trading fixes
function axr_trade_manager.npc_trade_buy_sell(npc)
   local id = npc and npc:id()
   local st = id and db.storage[id]
   if not (st) then
      return
   end

   if not (st.has_items_to_sell) then
      --printf("st.has_items_to_sell = nil!")
      return
   end

   if not (st.trade_items) then
      --printf("no items to sell")
      return
   end

   local smart = xr_gulag.get_npc_smart(npc)
   local npc_info = smart and smart.npc_info[id]
   if (npc_info) then
      npc_info.job.idle = time_global() + 20000
   end

   printf("- NPC Trade | Selling")

   local se_obj = alife_object(id)
   if not (se_obj) then
      return
   end

   -- Get the Trader
   local smart = xr_gulag.get_npc_smart(npc)
   local npc_info = smart and smart.npc_info[id]
   local seller_id = npc_info and npc_info.job and npc_info.job.seller_id
   local seller = seller_id and (db.storage[seller_id] and db.storage[seller_id].object or level.object_by_id(seller_id))
   printf("- NPC Trade | Trader = %s", seller and seller:name())
   
   -- SELL ITEMS
   local itm,itm_base_cost,buy_sell, slot, bw,can_sell
   for sec,count in pairs(st.trade_items) do
      -- demonized: fixed count loop to go down
      local count = tonumber(count) or 0
      for i=count, 1, -1 do
         itm = npc:object(sec)
         if (itm) then
            can_sell = true

            -- Make sure item is not his best weapon
            bw = npc:best_weapon()
            if (bw and bw:id() == itm:id()) then
               can_sell = false
            end

            -- Make sure item is not equipped
            for i=1,12 do
               slot = npc:item_in_slot(i)
               if (slot and slot:id() == itm:id()) then
                  can_sell = false
                  break
               end
            end

            buy_sell = axr_trade_manager.ini:r_string_ex("buy_sell",sec)
            if (buy_sell and buy_sell ~= "" and can_sell) then
               buy_sell = str_explode(buy_sell,",")
               
               -- Transfer the item
               if seller then
                  npc:transfer_item(itm, seller)
               else
                  alife_release_id(itm:id())
               end

               -- Give money
               itm_base_cost = ini_sys:r_float_ex(sec,"cost") or 30
               local money = math.floor(itm_base_cost * (tonumber(buy_sell[4]) or 1))
               npc:give_money(money)
               
               -- Increase NPC rank because he is a good boy
               game_statistics.increment_npc_statistic(npc,"items_sold")
               
               printf("- NPC Trade | %s sold [%s] for %s RU", npc:name(), sec, money)

               -- Only sell enough till reach keep-in-stock count (param 1)
               if (i <= tonumber(buy_sell[1])) then
                  break
               end
            end
         end
      end
   end
   
   empty_table(st.trade_items)
   st.has_items_to_sell = false

   -- BUY ITEMS
   local money = npc:money()
   if (money == nil or money <= 0) then
      return
   end

   if not (smart) then
      return
   end

   if (npc_info == nil or npc_info.job == nil) then
      return
   end

   if not (seller) then
      return
   end

   printf("- NPC Trade | Buying")

   local valid_items = utils_data.collect_section(axr_trade_manager.ini,"buy_sell",true)
   local item_list = {}

   local count = 0
   local function itr(npc,itm)
      local sec = itm:section()
      if (sec and valid_items[sec]) then
         -- count all valid items NPC has matching the buy_sell list
         item_list[sec] = item_list[sec] and item_list[sec] + 1 or 1
      end
   end

   npc:iterate_inventory(itr,npc)

   local bw = npc:best_weapon()
   bw = bw and bw:section()

   local bw_ammos = bw and parse_list(ini_sys,bw,"ammo_class",true)
   local buy_sell_items = {}
   local size_t = 0
   local buy_sell,total_cost
   for sec,v in pairs(valid_items) do
      buy_sell = axr_trade_manager.ini:r_string_ex("buy_sell",sec)
      if (buy_sell and buy_sell ~= "") then
         buy_sell = str_explode(buy_sell,",")

         itm_base_cost = ini_sys:r_float_ex(sec,"cost") or 30
         total_cost = math.floor(itm_base_cost * (tonumber(buy_sell[5]) or 1))

         -- If section is ammo, only buy ammo for best weapon
         if IsItem("ammo",sec) or (bw_ammos and bw_ammos[sec]) then
            if (item_list[sec]) then
               -- only buy enough to reach restock goals (param 3)
               for i=item_list[sec],tonumber(buy_sell[3]) do
                  if (money >= total_cost) then
                     size_t = size_t + 1
                     buy_sell_items[size_t] = sec
                     alife_create_item(sec, npc)
                     npc:transfer_money(total_cost,seller)
                     printf("- NPC Trade | %s bought [%s] for %s RU", npc:name(), sec, total_cost)
                     money = money - total_cost
                  end
               end
            else
               -- only buy enough to reach restock goals (param 3)
               for i=1,tonumber(buy_sell[3]) do
                  if (money >= total_cost) then
                     size_t = size_t + 1
                     buy_sell_items[size_t] = sec
                     alife_create_item(sec, npc)
                     npc:transfer_money(total_cost,seller)
                     printf("- NPC Trade | %s bought [%s] for %s RU", npc:name(), sec, total_cost)
                     money = money - total_cost
                  end
               end
            end
         end
      end

      -- NPC ran out of money, end loop
      if (money <= 0) then
         break
      end
   end
   
   if (#buy_sell_items > 0) then 
      if (dynamic_news_manager and ui_options.get("alife/dynamic_news/nearby_activity_news")) then 
         dynamic_news_manager.get_dynamic_news():BoughtItems(npc,seller,buy_sell_items)
      end
   end
end
