--[[
	Kute:
	
	Ordered Callback: Make callbacks don't select a random function to run each time (in pairs, order is randomized)
	Now it's ordered based on when you registered it.

	Example:
	When you have 2 scripts, "aaa.script" and "zzz.script" register its call back in "on_game_start" function. 
	The "zzz" one will run later, hence register its callback after aaa's.
	That's mean the order of the callback function would be: aaa first, then zzz.

	But what if aaa's callback want to override the changes of zzz's callback?
	Then, aaa can re-register its callback again, in a later time, like using TimeEvent or register its callback in the "actor_on_first_update", 
	to put it at a higher priority.

	Re-register callback will move the function to the highest priory, without the need to unregister it first

	This changes mainly to solve the clear priority issue in callbacks like `on_before_play_hud_sound` that require Lua code to return value to the engine.
	But can be used more to manipulate values in same callback without the fear of overwriting.
--]]


local next_index = {}
for name,v in pairs(axr_main.intercepts) do -- Copy the intercepts table for default callbacks
	next_index[name] = 1
end

axr_main.callback_add = function(name)
	if (not axr_main.intercepts[name]) then
		axr_main.intercepts[name] = {}
		next_index[name] = 1
	else
		printf("![axr_main callback_add] callback %s already exists!",name)
		callstack()
	end
end

axr_main.callback_set = function(name,func_or_userdata)
	if (func_or_userdata == nil) then 
		printf("![axr_main callback_set] trying to set callback %s to nil function!",name)
		callstack()
		return
	end
	if (axr_main.intercepts[name]) then
		axr_main.intercepts[name][func_or_userdata] = next_index[name]
		next_index[name] = next_index[name]+1
	else
		printf("![axr_main callback_set] callback %s doesn't exist!",name)
		callstack()
	end
end

axr_main.callback_unset = function(name,func_or_userdata)
	if (axr_main.intercepts[name]) then
		axr_main.intercepts[name][func_or_userdata] = nil
	else
		printf("![axr_main callback_unset] callback %s doesn't exist!",name)
		callstack()
	end
end

axr_main.make_callback = function(name,...)
	if (axr_main.intercepts[name]) then
		local functor = function(t,a,b)
			if type(t[a])~="number" then -- fix main_menu_on_innit have a bool value for some reason
				t[a] = next_index[name]
				next_index[name] = next_index[name]+1
			end
			if type(t[b])~="number" then
				t[b] = next_index[name]
				next_index[name] = next_index[name]+1
			end
			return t[a] < t[b] 
		end
		for func_or_userdata,v in spairs(axr_main.intercepts[name],functor) do 
			if (type(func_or_userdata) == "function") then 
				func_or_userdata(...)
			elseif (func_or_userdata[name]) then
				func_or_userdata[name](func_or_userdata,...)
			end
		end
	else
		printf("![axr_main make_callback] can't make callback to non existing intercept %s!",name)
		callstack()
	end
end