; =*= lang: macro/lisp.compile =*=

(var axr-main (require :axr_main))

(var PATTERN-FILE-PATH (. (require "scam/compiler") :PATTERN_FILE_PATH))

(var ignore
     {:_G.script true
      :class_registrator.script true
      :game_registrator.script true
      :ui_registrator.script true
      :ce_new_attachable_item.script true
      :ce_new_game_dm.script true
      :sim_faction_brain_human.script true
      :sim_faction_brain_mutant.script true
      :ce_switcher.script true
      :axr_main.script true
      :lua_help.script true
      :rx_gl.script true})

(fn axr-main.on_game_start []
  ;; Fetch a filesystem handle
  (var fs (getFS))

  ;; List scripts recursively
  (var flist
       (fs:file_list_open_ex "$game_scripts$"
                             FS.FS_ListFiles
                             "*.script"))

  ;; Accumulate on_game_start functions,
  ;; loading modules in the process
  (var start
       (faccumulate [start #nil
                     index 0 (- (flist:Size) 1)]
         (case-try (flist:GetAt index)
           (where file (> (file:Size) 0))
           (file:NameShort)
           
           (where file_name (not (. ignore file_name)))
           (file_name:match PATTERN-FILE-PATH)
           
           (path name ext)
           (let [file_name (string.gsub (.. path name) "\\" "/")]
             (pcall require file_name))
           
           (true { :on_game_start on-game-start })
           (let [old-start start]
             #(do (old-start)
                  (on-game-start)))

           (catch _ start))))

  ;; Call the result
  (start))

{}


