function expand(src, namespace_name)
   return string.format(
      [==[
local fennel = require("fennel")
table.insert(
    fennel["macro-searchers"],
    function(module_name)
        if module_name ~= "%s" then
            return
        end
        return function()
            return fennel.eval(
                [=[
                    %s
                ]=],
                {
                    correlate = true,
                    env = "_COMPILER",
                    useBitLib = true,
                    ["error-pinpoint"] = false,
                }
            )
        end
    end
)
package.loaded["%s"] = {}
      ]==],
      namespace_name,
      src,
      namespace_name
   )
end
