--- Sound distance options tree

-- Import smart constructors
options_builder.import_into(this)

PAGE = page {
    { id = "sound_distance" },
    track {
        id = "snd_max_distance_multiplier",
        def = 1.0,
        step = 0.1,
    },
    track {
        id = "snd_max_ai_distance_multiplier",
        def = 1.0,
        step = 0.1,
    },
    track {
        id = "step_sound_distance",
        def = 50,
        step = 1,
    },
}
