TAG_MACRO = "#macro "

local state = {
   default_macro = nil
}

function compile(src, script_name, namespace_name)
   print("compile", script_name, namespace_name)

   if string.sub(src, 1, #TAG_MACRO) == TAG_MACRO then
      src = string.sub(src, #TAG_MACRO + 1)
      local tag, rest = string.match(src, "([^%s]+)(%s+.*)")

      local mac = require_path("macro_" .. tag)
      print("mac:", mac)

      local out = mac(rest, namespace_name)
      print("out:", out)

      return out
   end

   if state.default_macro then
      print("loading via default macro")
      src = state.default_macro(src, namespace_name)
   else
      print("loading raw lua")
   end

   return loadstring(src, script_name)
end

function set_default_macro(mac)
   state.default_macro = mac
end

package.loaded["scam_compiler"] = {
   compile = compile,
   set_default_macro = set_default_macro
}
