local ini = ini_file("script.ltx")
if not ini then
    return
end

if not ini:section_exist("common") then
   error("Missing common section")
end

if not ini:line_exist("common", "class_registrators") then
   error("Missing class_registrators line")
end

local regs = ini:r_string("common", "class_registrators", "")
print("class registrators:", regs)

local fac = get_object_factory()
print("object_factory:", fac)

for reg_path in regs:gmatch("[^,]+") do
   print("reg_path:", reg_path)
   local reg = require_path(reg_path)
   print("reg:", reg)
   reg(fac)
end
