@echo off
echo Building xrRender_Vulkan...
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe" xrRender_Vulkan.vcxproj /p:Configuration=VerifiedDX11 /p:Platform=x64 /v:detailed
