-- xrs_facer faulty hit_callback
function xrs_facer.hit_callback(obj, amount, dir, who, bone_index)
   if not xrs_facer.Enabled then return end
   if bone_index == "from_death_callback" then return end
   if not db.storage[obj:id()].facer then return end

   if who and (IsStalker(who) or IsMonster(who)) and who:alive() and xrs_facer.check_enemy(who, obj) then
      local target_id = load_var(obj, "facer_target", nil)
      local target = target_id and db.storage[target_id] and db.storage[target_id].object
      if
         not target
         or obj:relation(target) ~= game_object.enemy
         or target:position():distance_to_sqr(obj:position()) > 4
      then
         save_var(obj, "facer_target", who:id())
         db.storage[obj:id()].facer.check_time = time_global() + xrs_facer.facer_sets.check_prd
      end
   end
end
